services:
  postgres:
    image: postgres:16-alpine
    container_name: job-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER:-jobapp}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-job_recommendation_db}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-jobapp} -d ${DB_NAME:-job_recommendation_db}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - job-net


  ml-service:
    build: ./ml-service
    container_name: job-ml-service
    restart: unless-stopped

    ports:
      - "6100:6100"

    networks:
      - job-net


  backend:
    build: ./backend
    container_name: job-backend
    restart: unless-stopped

    environment:
      PORT: 5000
      NODE_ENV: ${NODE_ENV:-development}

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-jobapp}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-job_recommendation_db}
      DB_SSL: ${DB_SSL:-false}

      JWT_SECRET: ${JWT_SECRET:-76bf555dd4c471b39148f38e037a44bca85b8d01204af073d38236e8cf3ffccf}
      JWT_EXPIRES_IN: 7d

      ML_SERVICE_URL: http://ml-service:6100
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN:-}

    ports:
      - "5050:5000"

    depends_on:
      postgres:
        condition: service_healthy
      ml-service:
        condition: service_started

    networks:
      - job-net


  frontend:
    build:
      context: ./frontend

      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5050/api}

    container_name: job-frontend
    restart: unless-stopped

    ports:
      - "3001:3000"

    depends_on:
      - backend

    networks:
      - job-net


volumes:
  postgres_data:


networks:
  job-net:
    driver: bridge